theme: jekyll-theme-cayman
title: ![GeoSim.AI](https://geosim.ai/) 
description: AI-driven Numerical Simulations in Geomechanics via Natural Language Instructions
markdown: kramdown
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge
